[features]
seeds = false
skip-lint = false
[programs.devnet]
myepicproject = "DfcrJsWXqUdydEgXC23u2y6TWLqW6rXma3GpSntXfHcR"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/asad/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js"
